### ISSUE TITLE
Message with multiple targets

### ISSUE THREAD

**Issue by xKiraiChan** [Er1807/VRCWS#3]
Currently, it seems a message can only have 1 target.
Sending a message to everyone in a world results in many messages being sent.
Instead of having to send multiple messages, `Message` could have a string[] field for all targets to send to, rather than just one.
`Target` could have a custom setter to manage a single item in the array to maintain compatibility with old code.

**Comment by Er1807** [comment]
This is intended. You can just send individual messages or create a wrapper that does it for you. But you still got a ratelimit of 40 messages per 5 sec.
