### ISSUE TITLE
Listen for user going online/offline

### ISSUE THREAD

**Issue by xKiraiChan** [Er1807/VRCWS#4]
For security reasons, the user coming online should verify the signature of the person listening.

For my use case, I want to know which people on my friends list are online.
It seems that currently there is no way to get online users, and polling all of these my friends would result in too many messages, excessively with larger friends lists.

Additionally, the only way to figure out someone is offline is by asking the server for that information, the server doesn't inform me when they go offline.

**Comment by Er1807** [comment]
The server has no knowledge of your friendlist so couldnt send you updates. This is also not inteded. With the current test code in https://github.com/Er1807/VRCWS/tree/teststuff something might be possible

**Comment by xKiraiChan** [comment]
My idea was that a client can ask the server to notify when a certain user-id sends the login event
When this user comes online the server will ask the person that came offline if the other client and their signature are allowed to know that they just came online.
